### ISSUE TITLE
Support new RAK firmware commands

### ISSUE THREAD

**Issue by ryanteck** [AmedeeBulle/pyrak811#8] opened 2020-05-07 12:33 UTC
The next batch of pHATs will be using the new RAK firmware that has a different command structure.

I'll be doing the work over the next few days to do this. The current plan is:

Keep current version as is and branched off.

New version will be say 1.0.0 and both will be downloadable from pypi.

Tutorials then say to either download the version if the user knows. Or run a curl command to run the automated installer which will then detect which version is on the board and install that.

We'll write guides on how to upgrade existing nodes.

**Comment by ryanteck** [comment] 2020-05-07 12:35
RAK Firmware we'll go for is 2020-03-09.

**Comment by AmedeeBulle** [comment] 2021-04-09 15:43
Duplicate of #15

**Closed by AmedeeBulle** 2021-04-09 15:43 UTC
